image: Ubuntu

build_script:
  - pwsh: Invoke-WebRequest 'https://dot.net/v1/dotnet-install.sh' -OutFile dotnet-install.sh; bash dotnet-install.sh --version 2.1.200; dotnet --version; [System.Environment]::SetEnvironmentVariable('PATH', "/home/appveyor/.dotnet:$PATH")
  - pwsh: dotnet --version
